[libraries]
spoon = "fr.inria.gforge.spoon:spoon-core:10.2.0"
jagr = "org.sourcegrade:jagr-launcher:0.6.2"
mockito = "org.mockito:mockito-core:4.9.0"
junit = "org.junit.jupiter:junit-jupiter:5.9.1"
asm = "org.ow2.asm:asm:9.4"
