[libraries]
spoon = "fr.inria.gforge.spoon:spoon-core:10.4.0"
jagr = "org.sourcegrade:jagr-launcher:0.9.0"
mockito = "org.mockito:mockito-core:5.3.1"
junit-core = "org.junit.jupiter:junit-jupiter:5.9.3"
asm = "org.ow2.asm:asm:9.5"
junit-pioneer = "org.junit-pioneer:junit-pioneer:1.7.1"

[bundles]
junit = ["junit-core", "junit-pioneer"]
